apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network

resources:
  - overlays/vlan10
  - overlays/vlan11
  - overlays/vlan12
  - overlays/vlan13
  - overlays/vlan20
  # Add new VLANs here, e.g:
  # - overlays/vlan30
